services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:git-a0068c4-ollama
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui:
